import "./globals.css";
import Nav from "@/app/(components)/Layouts/Nav";
import Footer from "@/app/(components)/Layouts/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
      <Nav />
      {children}
      <Footer year={new Date().getFullYear()}/>
      </body>
    </html>
  );
}
